### ISSUE TITLE
[Deno] should we move std imports to deps.ts?

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/stone-soup#128]
## What's the problem you want solved?
All the imports of external packages are in `deps.ts` except for imports from `deno.land/std`.

```
src/crypto/crypto-driver-chloride.ts
2:import { Buffer } from "https://deno.land/std@0.119.0/node/buffer.ts";

src/test/asserts.ts
1:export * from "https://deno.land/std@0.119.0/testing/asserts.ts";

src/test/universal/buffers.test.ts
1:import { Buffer } from "https://deno.land/std@0.119.0/node/buffer.ts";

src/util/buffers.ts
1:import { Buffer } from "https://deno.land/std@0.119.0/node/buffer.ts";
```

## Is there a solution you'd like to recommend?
Move those to `deps.ts` as well?  Or are we treating them differently because they're from the standard library?

**Comment by sgwilym** [comment]
I've kept them out because they are only used in tests or the node version, and when we include them in deps they'll be put into any web bundles we make. We should strive to keep big std libraries like `std/node` or testing out of the code that we want deno / browsers to consume.

**Comment by sgwilym** [comment]
Similarly, `which_runtime` is used exclusively in tests, so we should keep it there. Maybe it makes sense to have a `test_deps.ts`.

**Comment by cinnamon-bun** [comment]
Or maybe even `dep_node.ts`, `dep_deno.ts`, `dep_browser.ts` ?

I had moved which_runtime to deps.ts -- feel free to move it back or rearrange things, I don't know what I'm doing here.
