### ISSUE TITLE
set up Typedoc

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/stone-soup#30]
Copy the typedoc config over from the main earthstar repo (look in package.json)

Typedoc auto-generates HTML files documenting your classes.

**Comment by shravankb** [comment]
Hi @cinnamon-bun I would like to take this issue up!

**Comment by cinnamon-bun** [comment]
@shravankb Hi thanks!

You can fork this stone-soup repo, and modify the package.json to include the lines from here...

https://github.com/earthstar-project/earthstar/blob/main/package.json

that mention `typedoc`.  Then make a pull request and I'll merge it here.

**Comment by cinnamon-bun** [comment]
See also #139 "add JSDocs"

**Comment by sgwilym** [comment]
Superseded by #139
