### ISSUE TITLE
Copy over the glob and template querying code from classic Earthstar, and its tests

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/stone-soup#47]
This is code for querying Storage paths using glob patterns like `/chat/*.txt`, or template patterns like `/chat/{msgid}.txt`.

We're going to use it to make Layers easier to build.

As you copy this over you'll have to make a few changes:
* The Query object type is slightly different
* Our tests have different boilerplate at the top, look at other stone-soup tests to get that working
* There's a different way to create a Storage now, you have to provide it with a Crypto object etc.  Look at our other tests

The code to copy over:
https://github.com/earthstar-project/earthstar/blob/main/src/storage/queryHelpers.ts

Its tests:
https://github.com/earthstar-project/earthstar/blob/main/src/test/queryHelpers.test.ts

**Comment by tlowrimore** [comment]
@cinnamon-bun @sgwilym I'm in the process of migrating this functionality from Earthstar to Stone Soup. It appears Stone Soup does away with `IStorage`, preferring the use of `IStorageAsync` instead.  Is that correct?  If so, I'm aiming to remove a couple of synchronous functions (`queryByGlobSync` and `queryByTemplateSync`) from the helper.  Does that fit with the spirit of this issue?

**Comment by sgwilym** [comment]
@tlowrimore Sounds right to me! I don't think there's any way to achieve those methods with stone soup's asynchronous API.

**Comment by tlowrimore** [comment]
@sgwilym @cinnamon-bun Is this issue good to close?

**Comment by cinnamon-bun** [comment]
Yep, this was merged in #138
