### ISSUE TITLE
Consider other testing frameworks

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/stone-soup#8]
## The situation

We need to run our tests in all our environments: node, browser, deno.

Currently we use `tap` in node and `tape + browserify + browser-run` for browser tests.  This works just fine but the browser side is clunky, mostly because of `browser-run`.

## Reasons to stay with tap/tape

We have lots of tests already written with tape style assertions.

I like that tape is not responsible for building or running your code.  Your tests are just normal node programs that you can run by hand if you want to.  I only want one build pipeline to worry about.  It should be pretty easy to get tape running in deno.

## Consider...

How will we swap out or control which tests run in which environments?

Other test frameworks

[Karma](https://karma-runner.github.io/6.3/intro/how-it-works.html)
* Runs in a browser
* Only browsers, not Node
* Can be configured to run tape style tests in the browser, so we don't have to change our tests, we can use this as a replacement for browser-run.

[Jest](https://jestjs.io/)
* Our tests can be auto-migrated with [jest-codemods](https://github.com/skovhus/jest-codemods)
* Runs in Node.  No real browsers, uses JSDom instead.  Unless we can do something clever with [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) which seems to run a real browser.

[Intern](https://theintern.io/)
* runs in node and actual browsers
* you have to install a copy of Selenium on your machine
* docs are a bit confusing
* the name bothers me

**Comment by tlowrimore** [comment]
@cinnamon-bun @sgwilym How are we feeling about this now that we're using Deno and it's built-in test runner?

**Comment by sgwilym** [comment]
I feel pretty good about Deno.test. Its API is nearly the same as `tap`'s, and it works quickly.

The only thing we're missing is browser tests. Ideally I'd like something that works a bit like the Node tests do now: just take the Deno tests and run them in the browser. As we already have tests compiled for Node, maybe we can run them through something to put them in the browser too.

Eventually I think Deno will have this built-in.
